### Create a user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "Filerman@ee.com",
    "password": "Pass@1"
}

### Login User
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "Filermans@ee.com",
    "password": "Pass@1"
}

### Find User By Id
GET http://localhost:3000/auth/6

### Find User by Email
GET http://localhost:3000/auth?email=332e@ee.com&status=fhd

### Delete User
DELETE http://localhost:3000/auth/23322222

### Update User
PATCH http://localhost:3000/auth/6
content-type: application/json

{
    "password": "sipman@ee.com"
}