### Create a user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "dipoe@ee.com",
    "password": "WWWWWW"
}

### Find User By Id
GET http://localhost:3000/auth/2

### Find User by Email
GET http://localhost:3000/auth?email=maram@ee.com&status=fhd

### Delete User
DELETE http://localhost:3000/auth/5