### Create a user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "sam@ee.com",
    "password": "pass"
}

### Login User
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "sam@ee.com",
    "password": "pass"
}

### Get Current Signed-In User
GET http://localhost:3000/auth/whoami

### Signout User
POST http://localhost:3000/auth/signout

### Find User By Id
GET http://localhost:3000/auth/6

### Find User by Email
GET http://localhost:3000/auth?email=332e@ee.com&status=fhd

### Delete User
DELETE http://localhost:3000/auth/23322222

### Update User
PATCH http://localhost:3000/auth/6
content-type: application/json

{
    "password": "sipman@ee.com"
}

### Set Color
GET http://localhost:3000/auth/colors/eneioeioheoi

### Get Color
GET http://localhost:3000/auth/colors